version: "3.7"

services:

    composer:
        image: composer
        volumes:
            - .:/app


    phar:
        image: composer
        volumes:
            - .:/app
        entrypoint: /usr/local/bin/php -d phar.readonly=off phar-composer.phar
        command: build . ais-sdk.phar


    test:
        image: priorist/phpunit
        build:
            context: .
        entrypoint: vendor/bin/phpunit --bootstrap vendor/autoload.php --colors=always --whitelist src/Client --coverage-text
        command: tests
        working_dir: /app
        volumes:
            - .:/app
        environment:
            AIS_URL: ${AIS_URL}
            CLIENT_ID: ${CLIENT_ID}
            CLIENT_SECRET: ${CLIENT_SECRET}
            CLIENT_ID_USER: ${CLIENT_ID_USER}
            CLIENT_SECRET_USER: ${CLIENT_SECRET_USER}
            USER_LOGIN: ${USER_LOGIN}
            USER_PASSWORD: ${USER_PASSWORD}


    docs:
        image: phpdoc/phpdoc
        volumes:
            - .:/data
        command: -d ./src/Client -t ./docs --title "AIS SDK" --visibility "public"
